// Fonte única de módulos do sistema
export const MODULES = {
  DASHBOARD: 'dashboard',
  ATIVIDADES: 'atividades',
  FECHAMENTO_SEMANAL: 'fechamento_semanal',
  SUPERVISORES: 'supervisores',
  ANALISTAS: 'analistas',
  RANKING: 'ranking',
  QUIZZ_RELAMPAGO: 'quizz_relampago',
  AVALIACOES: 'avaliacoes',
  CERTIFICADOS: 'certificados',
  WAR_ROOM: 'war_room',
  MANUAL_SUPERVISOR: 'manual_supervisor',
  APROVACAO: 'aprovacao',
  GESTAO_USUARIOS: 'gestao_usuarios',
  LOGS_SISTEMA: 'logs_sistema',
};

export const MODULE_LABELS = {
  [MODULES.DASHBOARD]: 'Dashboard',
  [MODULES.ATIVIDADES]: 'Atividades',
  [MODULES.FECHAMENTO_SEMANAL]: 'Fechamento Semanal',
  [MODULES.SUPERVISORES]: 'Supervisores',
  [MODULES.ANALISTAS]: 'Analistas',
  [MODULES.RANKING]: 'Ranking',
  [MODULES.QUIZZ_RELAMPAGO]: 'Quizz Relâmpago',
  [MODULES.AVALIACOES]: 'Avaliações',
  [MODULES.CERTIFICADOS]: 'Certificados',
  [MODULES.WAR_ROOM]: 'War Room',
  [MODULES.MANUAL_SUPERVISOR]: 'Manual do Supervisor',
  [MODULES.APROVACAO]: 'Aprovação',
  [MODULES.GESTAO_USUARIOS]: 'Gestão de Usuários',
  [MODULES.LOGS_SISTEMA]: 'Logs do Sistema',
};

export const MODULE_PATHS = {
  [MODULES.DASHBOARD]: 'Dashboard',
  [MODULES.ATIVIDADES]: 'Atividades',
  [MODULES.FECHAMENTO_SEMANAL]: 'FechamentoSemanal',
  [MODULES.SUPERVISORES]: 'Supervisores',
  [MODULES.ANALISTAS]: 'Analistas',
  [MODULES.RANKING]: 'Ranking',
  [MODULES.QUIZZ_RELAMPAGO]: 'QuizzRelampago',
  [MODULES.AVALIACOES]: 'Avaliacoes',
  [MODULES.CERTIFICADOS]: 'Certificados',
  [MODULES.WAR_ROOM]: 'WarRoom',
  [MODULES.MANUAL_SUPERVISOR]: 'ManualSupervisor',
  [MODULES.APROVACAO]: 'Aprovacao',
  [MODULES.GESTAO_USUARIOS]: 'GestaoUsuarios',
  [MODULES.LOGS_SISTEMA]: 'Logs',
};

// Preset de permissões por role
export const ROLE_PRESETS = {
  admin: {
    [MODULES.DASHBOARD]: { visible: true, read: true, create: true, edit: true },
    [MODULES.ATIVIDADES]: { visible: true, read: true, create: true, edit: true },
    [MODULES.FECHAMENTO_SEMANAL]: { visible: true, read: true, create: true, edit: true },
    [MODULES.SUPERVISORES]: { visible: true, read: true, create: true, edit: true },
    [MODULES.ANALISTAS]: { visible: true, read: true, create: true, edit: true },
    [MODULES.RANKING]: { visible: true, read: true, create: true, edit: true },
    [MODULES.QUIZZ_RELAMPAGO]: { visible: true, read: true, create: true, edit: true },
    [MODULES.AVALIACOES]: { visible: true, read: true, create: true, edit: true },
    [MODULES.CERTIFICADOS]: { visible: true, read: true, create: true, edit: true },
    [MODULES.WAR_ROOM]: { visible: true, read: true, create: true, edit: true },
    [MODULES.MANUAL_SUPERVISOR]: { visible: true, read: true, create: true, edit: true },
    [MODULES.APROVACAO]: { visible: true, read: true, create: true, edit: true },
    [MODULES.GESTAO_USUARIOS]: { visible: true, read: true, create: true, edit: true },
    [MODULES.LOGS_SISTEMA]: { visible: true, read: true, create: true, edit: true },
  },
  supervisor: {
    [MODULES.DASHBOARD]: { visible: true, read: true, create: true, edit: true },
    [MODULES.ATIVIDADES]: { visible: true, read: true, create: true, edit: true },
    [MODULES.FECHAMENTO_SEMANAL]: { visible: true, read: true, create: true, edit: true },
    [MODULES.SUPERVISORES]: { visible: true, read: true, create: true, edit: true },
    [MODULES.ANALISTAS]: { visible: true, read: true, create: true, edit: true },
    [MODULES.RANKING]: { visible: true, read: true, create: true, edit: true },
    [MODULES.QUIZZ_RELAMPAGO]: { visible: true, read: true, create: true, edit: true },
    [MODULES.AVALIACOES]: { visible: true, read: true, create: true, edit: true },
    [MODULES.CERTIFICADOS]: { visible: true, read: true, create: true, edit: true },
    [MODULES.WAR_ROOM]: { visible: true, read: true, create: true, edit: true },
    [MODULES.MANUAL_SUPERVISOR]: { visible: true, read: true, create: true, edit: true },
    [MODULES.APROVACAO]: { visible: false, read: false, create: false, edit: false },
    [MODULES.GESTAO_USUARIOS]: { visible: false, read: false, create: false, edit: false },
    [MODULES.LOGS_SISTEMA]: { visible: false, read: false, create: false, edit: false },
  },
  analyst: {
    [MODULES.DASHBOARD]: { visible: false, read: false, create: false, edit: false },
    [MODULES.ATIVIDADES]: { visible: false, read: false, create: false, edit: false },
    [MODULES.FECHAMENTO_SEMANAL]: { visible: false, read: false, create: false, edit: false },
    [MODULES.SUPERVISORES]: { visible: false, read: false, create: false, edit: false },
    [MODULES.ANALISTAS]: { visible: false, read: false, create: false, edit: false },
    [MODULES.RANKING]: { visible: true, read: true, create: true, edit: true },
    [MODULES.QUIZZ_RELAMPAGO]: { visible: true, read: true, create: true, edit: true },
    [MODULES.AVALIACOES]: { visible: true, read: true, create: true, edit: true },
    [MODULES.CERTIFICADOS]: { visible: false, read: false, create: false, edit: false },
    [MODULES.WAR_ROOM]: { visible: false, read: false, create: false, edit: false },
    [MODULES.MANUAL_SUPERVISOR]: { visible: false, read: false, create: false, edit: false },
    [MODULES.APROVACAO]: { visible: false, read: false, create: false, edit: false },
    [MODULES.GESTAO_USUARIOS]: { visible: false, read: false, create: false, edit: false },
    [MODULES.LOGS_SISTEMA]: { visible: false, read: false, create: false, edit: false },
  },
  noc: {
    [MODULES.DASHBOARD]: { visible: false, read: false, create: false, edit: false },
    [MODULES.ATIVIDADES]: { visible: false, read: false, create: false, edit: false },
    [MODULES.FECHAMENTO_SEMANAL]: { visible: false, read: false, create: false, edit: false },
    [MODULES.SUPERVISORES]: { visible: false, read: false, create: false, edit: false },
    [MODULES.ANALISTAS]: { visible: false, read: false, create: false, edit: false },
    [MODULES.RANKING]: { visible: false, read: false, create: false, edit: false },
    [MODULES.QUIZZ_RELAMPAGO]: { visible: false, read: false, create: false, edit: false },
    [MODULES.AVALIACOES]: { visible: false, read: false, create: false, edit: false },
    [MODULES.CERTIFICADOS]: { visible: false, read: false, create: false, edit: false },
    [MODULES.WAR_ROOM]: { visible: true, read: true, create: false, edit: false },
    [MODULES.MANUAL_SUPERVISOR]: { visible: false, read: false, create: false, edit: false },
    [MODULES.APROVACAO]: { visible: false, read: false, create: false, edit: false },
    [MODULES.GESTAO_USUARIOS]: { visible: false, read: false, create: false, edit: false },
    [MODULES.LOGS_SISTEMA]: { visible: false, read: false, create: false, edit: false },
  },
};